### ISSUE TITLE
signtools error

### ISSUE THREAD

**Issue by wisepound** [avocode/electron-windows-autoupdate#4]
Hi 
The electron-windows-autoupdate is great,
I followed the exact steps and get the auto update work in my windows PC, but some how it wouldn't
work.
I have upload the code :https://github.com/100mubiao/auto-update

When I run build I got this error:

SC_KEY_PASSWORD is not defined, empty password will be used
No native production dependencies
Packaging for win32 x64 using electron 1.4.13 to dist\win-unpacked
Signing 100mubiao1.exe (certificate file "./certs/my_signing_key.pfx")

**Error: Exit code: 1. Command failed: C:\Users\Administrator\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-1.6.0\windows-6\signtool.exe sign /tr http://timestamp.comodoca.com/rfc3161 /f ./certs/my_signing_key.pfx /fd sha256 /td sha256 /d 100mubiao1 /du https://github.com/avocode/electron-windows-autoupdate /as E:\test\electron-windows-autoupdate\dist\win-unpacked\100mubiao1.exe
SignTool Error: An unexpected internal error has occurred.**

Done Adding Additional Store
Error information: "Error: SignerSign() failed." (-2147023436/0x800705b4)

SignTool Error: An unexpected internal error has occurred.**

    at E:\test\electron-windows-autoupdate\node_modules\.11.2.1@electron-builder-util\src\util.ts:76:16
    at ChildProcess.exithandler (child_process.js:209:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (E:\test\electron-windows-autoupdate\node_modules\.3.4.7@bluebird\js\release\debuggability.js:397:19)
    at Promise._then (E:\test\electron-windows-autoupdate\node_modules\.3.4.7@bluebird\js\release\promise.js:231:17)
    at Promise._passThrough (E:\test\electron-windows-autoupdate\node_modules\.3.4.7@bluebird\js\release\finally.js:91:17)
    at Promise.lastly.Promise.finally (E:\test\electron-windows-autoupdate\node_modules\.3.4.7@bluebird\js\release\finally.js:100:17)
    at new PromiseSpawn (E:\test\electron-windows-autoupdate\node_modules\.3.4.7@bluebird\js\release\generators.js:36:34)
    at E:\test\electron-windows-autoupdate\node_modules\.3.4.7@bluebird\js\release\generators.js:197:21
    at build (E:\test\electron-windows-autoupdate\node_modules\.11.2.3@electron-builder\out\builder.js:90:21)
    at Object.<anonymous> (E:\test\electron-windows-autoupdate\node_modules\.11.2.3@electron-builder\out\cli\build-cli.js:68:41)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

**Comment by vojtatranta** [comment]
Hi,
thank you for this question. But I fear I can't help you, I have never seen such problem. The error message is also not useful. I think this may be caused by some kind of problems with permission with the cert file? Or maybe the fail is corrupted. Maybe even electron-windows-auptupdate is someho broken - reinstall, maybe?
